name: Debug Event

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

jobs:
  debug:
    name: debug cd
    runs-on: ubuntu-latest
    steps:
      - name: Information Output
        run: |
          echo "EVENT_NAME: ${{ github.event_name }}"
          echo "REF_NAME: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "-------- FULL EVENT ---------"
          jq . $GITHUB_EVENT_PATH
